<?php
/**
 * @var Amasty\Hamenok\Block\Form\Form $block
 * @var Magento\Framework\Escaper $escaper;
 */
?>

<div>
    <form  action="<?= $block->getUrl($escaper->escapeHtml($block->getFormAction())); ?>" method="POST" data-mage-init='{"validation": {}}'
            class="<?= $escaper->escapeHtml($block->getForm()); ?> ">
        <div data-bind="scope: 'skuAutocomplete'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
         <?php if ($block->getIsEnabledQty()): ?>
                <label for="qty" class="<?= $escaper->escapeHtml($block->getLabel()); ?>">
                    Количество
                </label>
                <input type="number" name="qty" id="qty" class="<?= $escaper->escapeHtml($block->getInput()); ?> "
                       value="<?= $block->getDefaultValueQty(); ?>" data-validate='{"required":true, "integer":true, "validate-zero-or-greater":true}'/>
        <?php endif; ?>
        <button type="submit" class="<?= $escaper->escapeHtml($block->getBtn()); ?>">
            Отправить
        </button>
    </form>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "skuAutocomplete": {
                        "component": "Amasty_Hamenok/js/koAutocomplete",
                        "template": "Amasty_Hamenok/koAutocomplete",
                        "classLabel": "<?= $escaper->escapeHtml($block->getLabel()); ?>",
                        "classInput": "<?= $escaper->escapeHtml($block->getInput()); ?>"
                    }
                }
            }
        }
    }
</script>