<?php
/**
 * @var Amasty\Hamenok\Block\Timer\Timer $block
 * @var Magento\Framework\Escaper $escaper
 */
?>
<div data-bind="scope: 'stopwatch'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "stopwatch": {
                        "component": "Amasty_Hamenok/js/koStopwatch",
                        "template": "Amasty_Hamenok/koStopwatch"
                    }
                }
            }
        }
    }
</script>